#!/usr/bin/env Rscript

suppressPackageStartupMessages({
  library(argparse)
})

parser <- ArgumentParser(
  description = "Write a publication-ready TCR-seq methods paragraph with software versions."
)
parser$add_argument(
  "--output",
  default = "tcr_seek_methods.md",
  help = "Markdown output file [default: %(default)s]"
)
parser$add_argument(
  "--pipeline-version",
  default = "",
  help = "Optional tcr-seek pipeline version or release label"
)
parser$add_argument(
  "--container-image",
  default = "",
  help = "Optional Singularity/SIF image path used for the analysis"
)
parser$add_argument(
  "--container-source",
  default = "",
  help = "Optional Docker/OCI source image used to build the Singularity/SIF image"
)
parser$add_argument(
  "--clonotype-definition",
  default = "strict",
  help = "Clonotype definition reported for diversity analysis [default: %(default)s]"
)
args <- parser$parse_args()

package_version <- function(pkg) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    return("not installed")
  }
  as.character(utils::packageVersion(pkg))
}

first_version_line <- function(command, args = "--version") {
  value <- tryCatch(
    suppressWarnings(system2(command, args = args, stdout = TRUE, stderr = TRUE)),
    error = function(e) character()
  )
  value <- value[nzchar(value)]
  if (!length(value)) {
    return("not available")
  }
  value[[1]]
}

inspect_container_source <- function(container_image) {
  if (!nzchar(container_image)) {
    return("")
  }
  inspect <- tryCatch(
    suppressWarnings(system2("singularity", args = c("inspect", container_image), stdout = TRUE, stderr = TRUE)),
    error = function(e) character()
  )
  from_line <- grep("org\\.label-schema\\.usage\\.singularity\\.deffile\\.from:", inspect, value = TRUE)
  if (!length(from_line)) {
    return("")
  }
  source <- sub("^.*org\\.label-schema\\.usage\\.singularity\\.deffile\\.from:\\s*", "", from_line[[1]])
  source <- trimws(source)
  if (nzchar(source) && !grepl("^[a-z]+://", source)) {
    source <- paste0("docker://", source)
  }
  source
}

container_source <- if (nzchar(args$container_source)) {
  args$container_source
} else {
  inspect_container_source(args$container_image)
}

versions <- data.frame(
  Software = c(
    "tcr-seek",
    "Container image",
    "Container source",
    "R",
    "pRESTO",
    "Change-O",
    "IgBLAST",
    "seqkit",
    "immunarch",
    "vegan",
    "tidyverse",
    "argparse"
  ),
  Version = c(
    ifelse(nzchar(args$pipeline_version), args$pipeline_version, "not specified"),
    ifelse(nzchar(args$container_image), args$container_image, "not specified"),
    ifelse(nzchar(container_source), container_source, "not specified"),
    paste(R.version$major, R.version$minor, sep = "."),
    first_version_line("FilterSeq.py"),
    first_version_line("MakeDb.py"),
    first_version_line("igblastn", "-version"),
    first_version_line("seqkit", "version"),
    package_version("immunarch"),
    package_version("vegan"),
    package_version("tidyverse"),
    package_version("argparse")
  ),
  stringsAsFactors = FALSE
)

version_for <- function(software) {
  versions$Version[match(software, versions$Software)]
}

version_text <- function(software) {
  value <- version_for(software)
  if (is.na(value) || !nzchar(value) || value %in% c("not available", "not installed", "not specified")) {
    return(software)
  }
  paste0(software, " (", value, ")")
}

container_text <- if (nzchar(args$container_image) && nzchar(container_source)) {
  paste0("Singularity container built from ", container_source, " (SIF: ", args$container_image, ")")
} else if (nzchar(container_source)) {
  paste0("Singularity container built from ", container_source)
} else if (nzchar(args$container_image)) {
  paste0("Singularity container (", args$container_image, ")")
} else {
  "Singularity container"
}

methods <- paste0(
  "Bulk T-cell receptor sequencing data were processed with the ",
  version_text("tcr-seek"),
  " Snakemake workflow in a ",
  container_text,
  ". Paired FASTQ files were staged as sample-level read pairs and processed ",
  "with ",
  version_text("pRESTO"),
  ": reads were quality filtered at Q20, primers were identified ",
  "and masked or trimmed, read pairs were matched, molecular consensus ",
  "sequences were generated by barcode, paired consensus reads were assembled ",
  "against the immune reference, constant-region primers were annotated, and ",
  "identical sequences were collapsed while retaining clone counts. Collapsed ",
  "sequences with CONSCOUNT >= 2 were converted to FASTA with ",
  version_text("seqkit"),
  " and aligned to human TCR germline references with ",
  version_text("IgBLAST"),
  " through ",
  version_text("Change-O"),
  "; AIRR-format db-pass tables were generated with MakeDb.py. Repertoire tables were imported ",
  "with ",
  version_text("immunarch"),
  "::repLoad after merging sample metadata. Diversity metrics were ",
  "calculated in ",
  version_text("R"),
  " using ",
  version_text("vegan"),
  " from a clonotype abundance matrix based on the ",
  args$clonotype_definition,
  " clonotype definition. Reported metrics included observed richness, Shannon ",
  "diversity, Simpson diversity (1 - D), Pielou evenness, library size, effective ",
  "clonotypes, dominant clone fractions, and rarefied richness. Rarefaction was ",
  "performed at the minimum sample library size, defined as the row sum of the ",
  "clonotype abundance matrix."
)

output <- c(
  "# TCR-seq Methods",
  "",
  methods,
  ""
)

writeLines(output, args$output)
